language: bash

services:
- docker

env:
  matrix:
  - DRUPAL_VER=8 PHP_VER=7.3
    #  - DRUPAL_VER=8 PHP_VER=7.2
    #  - DRUPAL_VER=8 PHP_VER=7.1

script:
- set -e
- make test
- cp docker.mk Makefile
- tar -czf docker4drupal.tar.gz docker-compose.yml docker-sync.yml Makefile .env traefik.yml

# deploy:
#   provider: releases
#   api_key: $GITHUB_ACCESS_TOKEN
#   overwrite: true
#   skip_cleanup: true
#   file_glob: true
#   file:
#   - docker4drupal.tar.gz
#   on:
#     tags: true
#     condition: $GITHUB_RELEASE = 1

deploy:
  provider: heroku
  api_key: 
    secure: 46724aef-f7d0-4a15-96e0-1a7c33ab080c
  app: drupal-tv5
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - docker4drupal.tar.gz


notifications:
  email:
    recipients:
    - louis.pollin@tv5monde.org
    on_success: never
    on_failure: always
